branch-defaults:
  master:
    environment: flask-env
    group_suffix: null
global:
  application_name: e-lection-station
  branch: null
  default_ec2_keyname: stenbom-eb
  default_platform: python2.7
  default_region: eu-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
